apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-deployment
  labels:
    app: name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: name
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
        - name: name
          image: image-name:tag-name
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: name
  labels:
    app: name
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
  selector:
    app: name
